import type {
  AccountManagerVM,
  AccountSummaryVM,
  AppUserVM,
  BudgetManagerVM,
  BudgetProgressVM,
  CategoryManagerVM,
  CategoryListVM,
  CsvImportPreviewRow,
  DashboardMonthVM,
  DashboardOverviewVM,
  TransactionListVM,
  TransactionManagerVM,
} from "@/lib/view-models";

export const mockCurrentUser: AppUserVM = {
  id: "user-demo",
  name: "Fabio Rivera",
  email: "fabio@budgetbuddy.local",
  initials: "FR",
};

export const mockDashboardOverview: DashboardOverviewVM = {
  monthLabel: "July 2026",
  monthlyIncomeDisplay: "$8,420",
  monthlyExpenseDisplay: "$5,965",
  netCashFlowDisplay: "+$2,455",
  remainingBudgetDisplay: "$1,135",
  totalAccountBalanceDisplay: "$19,380",
  largestExpenseCategory: "Housing",
};

export const mockAccounts: AccountSummaryVM[] = [
  {
    id: "acct-checking",
    name: "Primary Checking",
    type: "checking",
    currentBalanceDisplay: "$6,480",
    status: "healthy",
  },
  {
    id: "acct-savings",
    name: "Emergency Savings",
    type: "savings",
    currentBalanceDisplay: "$12,900",
    status: "healthy",
  },
];

export const mockAccountManagerItems: AccountManagerVM[] = [
  {
    id: "acct-checking-main",
    name: "Primary Checking",
    institution: "Northline Credit Union",
    type: "checking",
    startingBalanceCents: 420000,
    startingBalanceDisplay: "$4,200.00",
    currentBalanceCents: 648000,
    currentBalanceDisplay: "$6,480.00",
    linkedTransactionCount: 24,
    lastUpdatedLabel: "today",
    note: "Main cash-flow account used for payroll, bills, and everyday spending.",
    status: "healthy",
  },
  {
    id: "acct-savings-emergency",
    name: "Emergency Savings",
    institution: "Northline Credit Union",
    type: "savings",
    startingBalanceCents: 1085000,
    startingBalanceDisplay: "$10,850.00",
    currentBalanceCents: 1290000,
    currentBalanceDisplay: "$12,900.00",
    linkedTransactionCount: 3,
    lastUpdatedLabel: "2 days ago",
    note: "Reserved for long-term cash buffer and monthly transfers.",
    status: "healthy",
  },
  {
    id: "acct-credit-card",
    name: "Travel Rewards Card",
    institution: "Summit Card Services",
    type: "credit_card",
    startingBalanceCents: -23500,
    startingBalanceDisplay: "-$235.00",
    currentBalanceCents: -48100,
    currentBalanceDisplay: "-$481.00",
    linkedTransactionCount: 0,
    lastUpdatedLabel: "yesterday",
    note: "Carryover balance is small, but this liability should stay visible.",
    status: "warning",
  },
];

export const mockCategories: CategoryListVM[] = [
  {
    id: "cat-housing",
    name: "Housing",
    type: "expense",
    color: "#D96C5F",
    icon: "home",
  },
  {
    id: "cat-salary",
    name: "Salary",
    type: "income",
    color: "#0F8B8D",
    icon: "wallet",
  },
];

export const mockCategoryManagerItems: CategoryManagerVM[] = [
  {
    id: "cat-housing-manager",
    name: "Housing",
    type: "expense",
    color: "#D96C5F",
    iconToken: "HS",
    linkedTransactionCount: 9,
    monthlyAverageCents: 225000,
    monthlyAverageDisplay: "$2,250.00",
    note: "Covers rent and related housing charges.",
  },
  {
    id: "cat-groceries-manager",
    name: "Groceries",
    type: "expense",
    color: "#4E8FC7",
    iconToken: "GR",
    linkedTransactionCount: 12,
    monthlyAverageCents: 78000,
    monthlyAverageDisplay: "$780.00",
    note: "Weekly grocery runs and pantry restocks.",
  },
  {
    id: "cat-transport-manager",
    name: "Transport",
    type: "expense",
    color: "#0F8B8D",
    iconToken: "TR",
    linkedTransactionCount: 6,
    monthlyAverageCents: 61000,
    monthlyAverageDisplay: "$610.00",
    note: "Fuel, transit passes, and occasional rideshares.",
  },
  {
    id: "cat-salary-manager",
    name: "Salary",
    type: "income",
    color: "#0F8B8D",
    iconToken: "SA",
    linkedTransactionCount: 4,
    monthlyAverageCents: 821000,
    monthlyAverageDisplay: "$8,210.00",
    note: "Primary payroll deposits.",
  },
  {
    id: "cat-freelance-manager",
    name: "Freelance",
    type: "income",
    color: "#D09A32",
    iconToken: "FL",
    linkedTransactionCount: 1,
    monthlyAverageCents: 65000,
    monthlyAverageDisplay: "$650.00",
    note: "Side work and occasional project payments.",
  },
];

export const mockTransactions: TransactionListVM[] = [
  {
    id: "txn-rent",
    dateDisplay: "Jul 1",
    merchant: "Park View Apartments",
    description: "Monthly rent",
    amountDisplay: "-$2,250",
    type: "expense",
    categoryName: "Housing",
    accountName: "Primary Checking",
  },
  {
    id: "txn-payroll",
    dateDisplay: "Jul 5",
    merchant: "Northline Studio",
    description: "Payroll deposit",
    amountDisplay: "+$4,210",
    type: "income",
    categoryName: "Salary",
    accountName: "Primary Checking",
  },
];

export const mockTransactionManagerItems: TransactionManagerVM[] = [
  {
    id: "txn-rent",
    date: "2026-07-01",
    dateDisplay: "Jul 1",
    merchant: "Park View Apartments",
    description: "Monthly rent",
    amountCents: -225000,
    amountDisplay: "-$2,250.00",
    type: "expense",
    categoryId: "cat-housing-manager",
    categoryName: "Housing",
    accountId: "acct-checking-main",
    accountName: "Primary Checking",
    notes: "Due on the first of every month.",
  },
  {
    id: "txn-payroll",
    date: "2026-07-05",
    dateDisplay: "Jul 5",
    merchant: "Northline Studio",
    description: "Payroll deposit",
    amountCents: 421000,
    amountDisplay: "$4,210.00",
    type: "income",
    categoryId: "cat-salary-manager",
    categoryName: "Salary",
    accountId: "acct-checking-main",
    accountName: "Primary Checking",
    notes: "Biweekly direct deposit.",
  },
  {
    id: "txn-grocery",
    date: "2026-07-08",
    dateDisplay: "Jul 8",
    merchant: "Westview Market",
    description: "Weekly groceries",
    amountCents: -15400,
    amountDisplay: "-$154.00",
    type: "expense",
    categoryId: "cat-groceries-manager",
    categoryName: "Groceries",
    accountId: "acct-checking-main",
    accountName: "Primary Checking",
    notes: "",
  },
  {
    id: "txn-freelance",
    date: "2026-07-12",
    dateDisplay: "Jul 12",
    merchant: "Freelance Client",
    description: "Landing page project",
    amountCents: 95000,
    amountDisplay: "$950.00",
    type: "income",
    categoryId: "cat-freelance-manager",
    categoryName: "Freelance",
    accountId: "acct-checking-main",
    accountName: "Primary Checking",
    notes: "Paid via bank transfer.",
  },
  {
    id: "txn-transfer",
    date: "2026-07-15",
    dateDisplay: "Jul 15",
    merchant: "Internal transfer",
    description: "Moved cash to savings",
    amountCents: 40000,
    amountDisplay: "$400.00",
    type: "transfer",
    categoryId: null,
    categoryName: "Transfer",
    accountId: "acct-savings-emergency",
    accountName: "Emergency Savings",
    notes: "Transfer destination represented in mock only.",
  },
  {
    id: "txn-fuel",
    date: "2026-07-18",
    dateDisplay: "Jul 18",
    merchant: "City Fuel",
    description: "Weekend fuel top-up",
    amountCents: -6200,
    amountDisplay: "-$62.00",
    type: "expense",
    categoryId: "cat-transport-manager",
    categoryName: "Transport",
    accountId: "acct-credit-card",
    accountName: "Travel Rewards Card",
    notes: "",
  },
];

export const mockBudgets: BudgetProgressVM[] = [
  {
    id: "budget-housing",
    categoryName: "Housing",
    limitDisplay: "$2,500",
    spentDisplay: "$2,250",
    remainingDisplay: "$250",
    progressPercent: 90,
    status: "near",
  },
  {
    id: "budget-groceries",
    categoryName: "Groceries",
    limitDisplay: "$700",
    spentDisplay: "$410",
    remainingDisplay: "$290",
    progressPercent: 58,
    status: "under",
  },
];

export const mockBudgetManagerItems: BudgetManagerVM[] = [
  {
    id: "budget-housing-july",
    categoryId: "cat-housing-manager",
    categoryName: "Housing",
    categoryColor: "#D96C5F",
    month: "2026-07",
    monthLabel: "July 2026",
    limitAmountCents: 250000,
    limitDisplay: "$2,500.00",
    note: "Rent plus any small housing maintenance items.",
  },
  {
    id: "budget-groceries-july",
    categoryId: "cat-groceries-manager",
    categoryName: "Groceries",
    categoryColor: "#4E8FC7",
    month: "2026-07",
    monthLabel: "July 2026",
    limitAmountCents: 70000,
    limitDisplay: "$700.00",
    note: "Weekly groceries and household pantry restocks.",
  },
  {
    id: "budget-transport-july",
    categoryId: "cat-transport-manager",
    categoryName: "Transport",
    categoryColor: "#0F8B8D",
    month: "2026-07",
    monthLabel: "July 2026",
    limitAmountCents: 50000,
    limitDisplay: "$500.00",
    note: "Fuel and any transit top-ups for the month.",
  },
  {
    id: "budget-housing-june",
    categoryId: "cat-housing-manager",
    categoryName: "Housing",
    categoryColor: "#D96C5F",
    month: "2026-06",
    monthLabel: "June 2026",
    limitAmountCents: 250000,
    limitDisplay: "$2,500.00",
    note: "Standard monthly rent envelope.",
  },
  {
    id: "budget-groceries-june",
    categoryId: "cat-groceries-manager",
    categoryName: "Groceries",
    categoryColor: "#4E8FC7",
    month: "2026-06",
    monthLabel: "June 2026",
    limitAmountCents: 65000,
    limitDisplay: "$650.00",
    note: "Lower target set for summer meal planning.",
  },
];

export const mockCsvPreviewRows: CsvImportPreviewRow[] = [
  {
    id: "csv-1",
    dateDisplay: "2026-07-03",
    description: "Morning Roast",
    amountDisplay: "-$8.90",
    type: "expense",
    status: "valid",
    message: "Ready to import",
  },
  {
    id: "csv-2",
    dateDisplay: "2026-07-04",
    description: "Transfer",
    amountDisplay: "+$500.00",
    type: "income",
    status: "review",
    message: "Category needs confirmation",
  },
];

export const dashboardMonthOptions = [
  { value: "2026-07", label: "July 2026" },
  { value: "2026-06", label: "June 2026" },
  { value: "2026-05", label: "May 2026" },
];

const dashboardDataByMonth: Record<string, DashboardMonthVM> = {
  "2026-07": {
    id: "2026-07",
    label: "July 2026",
    summary: mockDashboardOverview,
    categorySpend: [
      {
        id: "housing",
        label: "Housing",
        valueDisplay: "$2,250",
        sharePercent: 38,
        color: "#D96C5F",
      },
      {
        id: "groceries",
        label: "Groceries",
        valueDisplay: "$820",
        sharePercent: 14,
        color: "#4E8FC7",
      },
      {
        id: "transport",
        label: "Transport",
        valueDisplay: "$610",
        sharePercent: 10,
        color: "#0F8B8D",
      },
      {
        id: "utilities",
        label: "Utilities",
        valueDisplay: "$485",
        sharePercent: 8,
        color: "#D09A32",
      },
      {
        id: "other",
        label: "Other",
        valueDisplay: "$1,800",
        sharePercent: 30,
        color: "#93A7BC",
      },
    ],
    incomeVsExpense: [
      {
        id: "may",
        label: "May",
        income: 7350,
        incomeDisplay: "$7,350",
        expense: 5580,
        expenseDisplay: "$5,580",
      },
      {
        id: "jun",
        label: "June",
        income: 8010,
        incomeDisplay: "$8,010",
        expense: 6015,
        expenseDisplay: "$6,015",
      },
      {
        id: "jul",
        label: "July",
        income: 8420,
        incomeDisplay: "$8,420",
        expense: 5965,
        expenseDisplay: "$5,965",
      },
    ],
    dailySpending: [
      { id: "d1", label: "1", amount: 122, valueDisplay: "$122" },
      { id: "d5", label: "5", amount: 310, valueDisplay: "$310" },
      { id: "d9", label: "9", amount: 210, valueDisplay: "$210" },
      { id: "d13", label: "13", amount: 460, valueDisplay: "$460" },
      { id: "d17", label: "17", amount: 190, valueDisplay: "$190" },
      { id: "d21", label: "21", amount: 520, valueDisplay: "$520" },
      { id: "d25", label: "25", amount: 280, valueDisplay: "$280" },
      { id: "d29", label: "29", amount: 335, valueDisplay: "$335" },
    ],
    recentTransactions: [
      ...mockTransactions,
      {
        id: "txn-groceries",
        dateDisplay: "Jul 8",
        merchant: "Westview Market",
        description: "Weekly groceries",
        amountDisplay: "-$154",
        type: "expense",
        categoryName: "Groceries",
        accountName: "Primary Checking",
      },
      {
        id: "txn-electric",
        dateDisplay: "Jul 10",
        merchant: "Gridline Energy",
        description: "Electric bill",
        amountDisplay: "-$118",
        type: "expense",
        categoryName: "Utilities",
        accountName: "Primary Checking",
      },
    ],
    budgets: mockBudgets,
    upcomingRecurring: [
      {
        id: "recur-rent",
        label: "Rent",
        nextDateDisplay: "Aug 1",
        frequencyLabel: "Monthly",
        amountDisplay: "$2,250",
      },
      {
        id: "recur-internet",
        label: "Internet",
        nextDateDisplay: "Jul 28",
        frequencyLabel: "Monthly",
        amountDisplay: "$79",
      },
      {
        id: "recur-paycheck",
        label: "Paycheck",
        nextDateDisplay: "Jul 31",
        frequencyLabel: "Biweekly",
        amountDisplay: "$2,105",
      },
    ],
    goal: {
      id: "goal-emergency-fund",
      name: "Emergency fund",
      currentAmountDisplay: "$12,900",
      targetAmountDisplay: "$18,000",
      remainingAmountDisplay: "$5,100",
      progressPercent: 72,
      targetDateDisplay: "Dec 2026",
    },
  },
  "2026-06": {
    id: "2026-06",
    label: "June 2026",
    summary: {
      monthLabel: "June 2026",
      monthlyIncomeDisplay: "$8,010",
      monthlyExpenseDisplay: "$6,015",
      netCashFlowDisplay: "+$1,995",
      remainingBudgetDisplay: "$820",
      totalAccountBalanceDisplay: "$17,110",
      largestExpenseCategory: "Housing",
    },
    categorySpend: [
      {
        id: "housing-june",
        label: "Housing",
        valueDisplay: "$2,250",
        sharePercent: 37,
        color: "#D96C5F",
      },
      {
        id: "groceries-june",
        label: "Groceries",
        valueDisplay: "$760",
        sharePercent: 13,
        color: "#4E8FC7",
      },
      {
        id: "transport-june",
        label: "Transport",
        valueDisplay: "$580",
        sharePercent: 10,
        color: "#0F8B8D",
      },
      {
        id: "subscriptions-june",
        label: "Subscriptions",
        valueDisplay: "$325",
        sharePercent: 5,
        color: "#D09A32",
      },
      {
        id: "other-june",
        label: "Other",
        valueDisplay: "$2,100",
        sharePercent: 35,
        color: "#93A7BC",
      },
    ],
    incomeVsExpense: [
      {
        id: "apr",
        label: "Apr",
        income: 7150,
        incomeDisplay: "$7,150",
        expense: 5420,
        expenseDisplay: "$5,420",
      },
      {
        id: "may-2",
        label: "May",
        income: 7350,
        incomeDisplay: "$7,350",
        expense: 5580,
        expenseDisplay: "$5,580",
      },
      {
        id: "jun-2",
        label: "June",
        income: 8010,
        incomeDisplay: "$8,010",
        expense: 6015,
        expenseDisplay: "$6,015",
      },
    ],
    dailySpending: [
      { id: "jd1", label: "2", amount: 145, valueDisplay: "$145" },
      { id: "jd5", label: "6", amount: 260, valueDisplay: "$260" },
      { id: "jd9", label: "10", amount: 340, valueDisplay: "$340" },
      { id: "jd13", label: "14", amount: 215, valueDisplay: "$215" },
      { id: "jd17", label: "18", amount: 405, valueDisplay: "$405" },
      { id: "jd21", label: "22", amount: 380, valueDisplay: "$380" },
      { id: "jd25", label: "26", amount: 195, valueDisplay: "$195" },
      { id: "jd29", label: "30", amount: 285, valueDisplay: "$285" },
    ],
    recentTransactions: [
      {
        id: "jun-salary",
        dateDisplay: "Jun 28",
        merchant: "Northline Studio",
        description: "Payroll deposit",
        amountDisplay: "+$4,005",
        type: "income",
        categoryName: "Salary",
        accountName: "Primary Checking",
      },
      {
        id: "jun-dining",
        dateDisplay: "Jun 25",
        merchant: "Harbor Table",
        description: "Dinner with friends",
        amountDisplay: "-$86",
        type: "expense",
        categoryName: "Dining",
        accountName: "Primary Checking",
      },
      {
        id: "jun-fuel",
        dateDisplay: "Jun 21",
        merchant: "City Fuel",
        description: "Fuel stop",
        amountDisplay: "-$62",
        type: "expense",
        categoryName: "Transport",
        accountName: "Primary Checking",
      },
    ],
    budgets: [
      {
        id: "budget-housing-june",
        categoryName: "Housing",
        limitDisplay: "$2,500",
        spentDisplay: "$2,250",
        remainingDisplay: "$250",
        progressPercent: 90,
        status: "near",
      },
      {
        id: "budget-dining-june",
        categoryName: "Dining",
        limitDisplay: "$350",
        spentDisplay: "$390",
        remainingDisplay: "-$40",
        progressPercent: 111,
        status: "over",
      },
    ],
    upcomingRecurring: [
      {
        id: "june-rent",
        label: "Rent",
        nextDateDisplay: "Jul 1",
        frequencyLabel: "Monthly",
        amountDisplay: "$2,250",
      },
      {
        id: "june-paycheck",
        label: "Paycheck",
        nextDateDisplay: "Jul 3",
        frequencyLabel: "Biweekly",
        amountDisplay: "$2,005",
      },
    ],
    goal: {
      id: "goal-emergency-fund-june",
      name: "Emergency fund",
      currentAmountDisplay: "$11,050",
      targetAmountDisplay: "$18,000",
      remainingAmountDisplay: "$6,950",
      progressPercent: 61,
      targetDateDisplay: "Dec 2026",
    },
  },
  "2026-05": {
    id: "2026-05",
    label: "May 2026",
    summary: {
      monthLabel: "May 2026",
      monthlyIncomeDisplay: "$0",
      monthlyExpenseDisplay: "$0",
      netCashFlowDisplay: "$0",
      remainingBudgetDisplay: "$0",
      totalAccountBalanceDisplay: "$15,115",
      largestExpenseCategory: "No data yet",
    },
    categorySpend: [],
    incomeVsExpense: [
      {
        id: "may-empty",
        label: "May",
        income: 0,
        incomeDisplay: "$0",
        expense: 0,
        expenseDisplay: "$0",
      },
    ],
    dailySpending: [],
    recentTransactions: [],
    budgets: [],
    upcomingRecurring: [],
    goal: {
      id: "goal-may",
      name: "Emergency fund",
      currentAmountDisplay: "$10,000",
      targetAmountDisplay: "$18,000",
      remainingAmountDisplay: "$8,000",
      progressPercent: 56,
      targetDateDisplay: "Dec 2026",
    },
  },
};

export function getDashboardMonthData(month: string | undefined) {
  return dashboardDataByMonth[month ?? ""] ?? dashboardDataByMonth["2026-07"];
}
